[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
tracing = "0.1.44"
tracing-subscriber = "0.3.23"
vrl = { version = "0.31.0", default-features = false, features = ["datadog_grok", "stdlib-base"] }
thiserror = "2.0.11"
axum = "0.7"
tokio = { version = "1.37", features = ["rt-multi-thread", "macros", "net", "time"] }
tower = { version = "0.5", features = ["limit"] }
tower-http = { version = "0.6", features = ["fs", "trace"] }
